# Generated by Django 5.2.5 on 2025-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpValidation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('rut_completo', models.CharField(db_index=True, max_length=12, unique=True)),
                ('razon_social', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
