# Generated by Django 5.2.5 on 2025-10-09 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0003_companyinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del empleo/posicion ofrecida', max_length=200)),
                ('mode', models.CharField(choices=[('hybrid', 'Hibrido'), ('remote', 'Remoto'), ('in-person', 'Presencial')], max_length=20)),
                ('level', models.CharField(choices=[('senior', 'Senior'), ('mid-sen', 'Mid-Senior'), ('jun-mid', 'Junior-Mid'), ('junior', 'Junior')], max_length=20)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(max_length=255)),
                ('Time_start', models.TimeField()),
                ('Time_end', models.TimeField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JFlex.company')),
                ('habilities', models.ManyToManyField(to='JFlex.hability')),
            ],
        ),
    ]
