# Generated by Django 5.2.5 on 2025-10-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0004_hability_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hability',
            new_name='Ability',
        ),
    ]
