# Generated by Django 5.2.5 on 2025-10-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0005_rename_hability_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='habilities',
            new_name='abilities',
        ),
    ]
