# Generated by Django 5.2.5 on 2025-10-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0006_rename_habilities_job_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='color',
            field=models.CharField(choices=[('grey', 'Gris'), ('red', 'Rojo'), ('orange', 'Naranja'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('teal', 'Verde Azulado'), ('blue', 'Azul'), ('indigo', 'Azul Marino'), ('purple', 'Morado'), ('pink', 'Rosa')], default='grey', max_length=50),
        ),
    ]
