# Generated by Django 5.2.5 on 2025-10-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JFlex', '0007_ability_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='color',
            field=models.CharField(choices=[('gray', 'Gris'), ('red', 'Rojo'), ('orange', 'Naranja'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('teal', 'Verde Azulado'), ('blue', 'Azul'), ('indigo', 'Azul Marino'), ('purple', 'Morado'), ('pink', 'Rosa')], default='gray', max_length=50),
        ),
    ]
